import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Aleo } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";
import { HeaderPagePresenter } from "@/presenters/headerPage-presenter";
import { Toaster } from "@/components/ui/sonner";
import UserSync from "@/utils/userSync";

const aleoSans = Aleo({
  variable: "--font-aleo-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <UserSync />
          <Toaster position="top-center" />
          <HeaderPagePresenter>{children}</HeaderPagePresenter>
        </StoreProvider>
      </body>
    </html>
  );
}
