import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Aleo } from "next/font/google"
import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";
import {HeaderPagePresenter} from '@/presenters/headerPage-presenter';

const aleoSans = Aleo({
  variable: "--font-aleo-sans",
  subsets: ["latin"],
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <HeaderPagePresenter>{children}</HeaderPagePresenter>
        </StoreProvider>
      </body>
    </html>
  );
}
